# docker compose file for development with visual studio code
services:

  geoportal:
    # entrypoint: >
    #   /bin/sh -c "python -u -m debugpy --listen 0.0.0.0:5678 /opt/mrmap/manage.py makemigrations accounts registry notify"
    # entrypoint: >
    #   /bin/sh -c "python -u -m debugpy --listen 0.0.0.0:5678 /opt/mrmap/manage.py sync_pgviews --force"
    # entrypoint: >
    #   /bin/bash -c "python /opt/mrmap/manage.py graph_models -a -g -o models.png"
    # entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
    #   /opt/mrmap/manage.py squashmigrations registry 0002"
    # entrypoint: >
    #  /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678 /opt/mrmap/manage.py migrate"
    #entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
    #   /opt/mrmap/manage.py loaddata test_users"
    # entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
    #   /opt/mrmap/manage.py dumpdata --natural-foreign --natural-primary registry
    #   > fixture.json"
    command: >
      /bin/sh -c "python -u -m debugpy --listen 0.0.0.0:5678 /opt/mrmap/manage.py runserver 0.0.0.0:8001"

    ports:
      - "0.0.0.0:3001:5678"
      - "0.0.0.0:8001:8001"
